# Set Phoesion Glow Prism image as base
FROM phoesion/phoesion.glow.prism:latest

# Create configs dir
RUN mkdir -p /etc/phoesion/glow/prism

# COPY configs.json to etc
COPY configs.json /etc/phoesion/glow/prism/configs.json