<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    

    
    <ItemGroup>
        <PackageReference Include="Phoesion.Glow.SDK.AspAdapter" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly.SrvHost.DotNet.AppHost" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.ReactorDebugger" Version="2.1.4" Condition="'$(GlowPublishing)'!='true'"/>
    </ItemGroup>
    

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.0.0" />
    </ItemGroup>

	<ItemGroup>
        <ProjectReference Include="..\Foompany.Services.HelloWorld.Api\Foompany.Services.HelloWorld.API.csproj" />
	</ItemGroup>
	
</Project>
