<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    

    
    <ItemGroup>
        <PackageReference Include="Phoesion.Glow.SDK.Firefly" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.AspAdapter" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly.SrvHost.DotNet.AppHost" Version="2.1.4" />
        <PackageReference Include="Phoesion.Glow.SDK.ReactorDebugger" Version="2.1.4" Condition="'$(GlowPublishing)'!='true'"/>
    </ItemGroup>
    

    <ItemGroup>
        <PackageReference Include="Sentry.AspNetCore" Version="5.4.0" />
    </ItemGroup>

</Project>
