<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net8.0;net7.0;net6.0</TargetFrameworks>
        <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    </PropertyGroup>

    

    
      <ItemGroup>
        <PackageReference Include="Phoesion.Glow.SDK.Firefly" Version="2.5.3" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly.SrvHost.DotNet.AppHost" Version="2.5.3" />
        <PackageReference Include="Phoesion.Glow.SDK.ReactorDebugger" Version="2.5.3" Condition="'$(GlowPublishing)'!='true'"/>
      </ItemGroup>
    

</Project>
