apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: firefly
    quantumspace: "1"
    servicename: goservice