apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom-retain

provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

#parameters:
#  type: gp2
#provisioner: kubernetes.io/aws-ebs
#volumeBindingMode: Immediate
#reclaimPolicy: Retain
#allowVolumeExpansion: true

