apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  labels:
    app: GlowApp
spec:
  serviceName: lighthouse
  replicas: 1 # CAUTION: Only one lighthouse at most should be running at any time in the cluster
  selector:
    matchLabels:
      service: lighthouse
  template:
    metadata:
      labels:
        app: GlowApp
        service: lighthouse
    spec:
      containers:
        - name: lighthouse
          image: phoesion/phoesion.glow.lighthouse
          ports:
            - containerPort: 15000
              protocol: TCP
              name: lh-spchannel
            - containerPort: 15001
              protocol: TCP
              name: lh-webui
            - containerPort: 15002
              protocol: TCP
              name: lh-webui2         
            - containerPort: 14000
              protocol: TCP
              name: p2p
          env:
            - name: LIGHTHOUSE_KaleidoscopeConnectionString
              value: "Host=kaleidoscope"
            - name: LIGHTHOUSE_DefaultUser__Username
              value: "admin"
            - name: LIGHTHOUSE_DefaultUser__Name
              value: "Administrator"
            - name: LIGHTHOUSE_DefaultUser__Description
              value: "Default administrator account created from configs"
            - name: LIGHTHOUSE_DefaultUser__Email
              value: "admin@myorganization.com" #CONFIG: Add email for default user
            - name: LIGHTHOUSE_DefaultUser__Password
              value: "123qweASD!" #CONFIG: Change password
            #- name: LIGHTHOUSE_DefaultUser__SshKey
            #  value: "" #CONFIG: Add public ssh key for default user
            #- name: LIGHTHOUSE_EntityAuthKey
            #  value: "" #CONFIG: Add lighthouse auth key (or get from secrets. like bellow)
          envFrom:
            - secretRef:
                name: lighthouse-authkey
          volumeMounts:
            - name: lighthouse-volume
              mountPath: /data
      # CAUTION: use the commented 'volumeClaimTemplates' section bellow for persistent storage
      volumes:
        - name: lighthouse-volume
          emptyDir: {}
#     volumeClaimTemplates:
#       - metadata:
#           name: lighthouse-volume
#         spec:
#           accessModes: [ "ReadWriteOnce" ]
#           storageClassName: custom-retain
#           resources:
#             requests:
#               storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: lighthouse
  labels:
    app: GlowApp
    service: lighthouse
spec:
  ports:
    # Lighthouse Port
    - port: 15000
      targetPort: lh-spchannel
      protocol: TCP
      name: lh-spchannel
    # Lighthouse WebUI port (http)
    - port: 15001
      name: lh-webui
      targetPort: lh-webui
      protocol: TCP
    # Lighthouse WebUI port (https)
    - port: 15002
      name: lh-webui2
      targetPort: lh-webui2
      protocol: TCP
  selector:
    service: lighthouse