apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    operator: glow-operator
    entitytype: firefly-operator
  name: firefly-operator-mygroup
spec:
  serviceName: firefly-operator-mygroup
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: glow-operator
  template:
    metadata:
      labels:
        operator: glow-operator
    spec:
      serviceAccountName: glow-operator
      containers:
        - name: firefly-operator-mygroup
          image: firefly.k8s.operator:dev
          imagePullPolicy: Never
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FIREFLY_KaleidoscopeConnectionString
              value: "Host=kaleidoscope"            
            # This entity will ONLY serve a specific service group in a specific quantum space
            - name: FIREFLY_QuantumSpace
              value: Default
            - name: FIREFLY_ServiceGroup
              value: MyGroup
            - name: FIREFLY_ServiceYamlFile
              value: "/configs/deployment.yaml"  # will be loaded from mygroup_service_base-deployment.yaml config map (and base-deployment volume below)
          envFrom:
            - secretRef:
                name: firefly-authkey
          ports:
            - containerPort: 14000
              name: p2p
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi    
          volumeMounts:
          - name: base-deployment
            mountPath: /configs
      volumes:
        - name: base-deployment
          configMap:
            name: mygroup-deployment.yaml
      terminationGracePeriodSeconds: 20
      automountServiceAccountToken: true 

