---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app-instance: firefly-ephemeral
  template:
    metadata:
      labels:
        app: firefly
        app-instance: firefly-ephemeral
    spec:
      containers:
      - name: firefly-ephemeral
        image: phoesion/phoesion.glow.firefly:0.0.296-debian
        resources:
          requests:
            ephemeral-storage: "4Gi"
          limits:
            ephemeral-storage: "16Gi"
        env:
        - name: FIREFLY_IsEphemeral
          value: "true"
        - name: FIREFLY_DataPath
          value: "/data/firefly"
        - name: FIREFLY_KaleidoscopeConnectionString
          value: "Host=kaleidoscope-headless"
        - name: FIREFLY_EntityAuthKey
          value: "" #CONFIG: Add firefly auth key
        volumeMounts:
        - name: firefly-ephemeral-vol
          mountPath: /data/firefly
      volumes:
      - name: firefly-ephemeral-vol
        emptyDir: {}
