# Set Phoesion Glow Kaleidoscope image as base
FROM phoesion/phoesion.glow.kaleidoscope:latest

# Create configs dir
RUN mkdir -p /etc/phoesion/glow/kaleidoscope

# COPY configs.json to etc
COPY ./configs.json /etc/phoesion/glow/kaleidoscope/configs.json