<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    

    
    <ItemGroup>
        <PackageReference Include="Phoesion.Glow.SDK.Firefly.Logging.Serilog" Version="2.5.2" />
        <PackageReference Include="Phoesion.Glow.SDK.AspAdapter" Version="2.5.2" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly" Version="2.5.2" />
        <PackageReference Include="Phoesion.Glow.SDK.Firefly.SrvHost.DotNet.AppHost" Version="2.5.2" />
        <PackageReference Include="Phoesion.Glow.SDK.ReactorDebugger" Version="2.5.2" Condition="'$(GlowPublishing)'!='true'"/>
    </ItemGroup>
    

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    </ItemGroup>

</Project>
